#! /bin/sh
#
# network.sample $Revision$ $Date$ (David Hinds)
#
# Initialize or shutdown a PCMCIA ethernet adapter
#
# This script should be invoked with two arguments.  The first is the
# action to be taken, either "start", "stop", or "restart".  The
# second is the network interface name.

action=$1
device=$2

case "${action:?}" in
'start')
	/sbin/ifup ${device}
    ;;
'stop')
	/sbin/ifdown ${device}
    ;;
'restart')
	/sbin/ifdown ${device} ; /sbin/ifup ${device}
    ;;
esac
